Multi servo
WyliodrinEmbeddedIoT/tock pull request #17
Opened 2024-09-11 12:59 UTC by inesmaria08

### Pull Request Overview

This pull request adds the option to change the angle of multiple servomotors

### Testing Strategy

This pull request was tested on a raspberry pi pico (using a Pico Explorer Base and a SG90 servo motor).

### TODO or Help Wanted

This pull request needs feedback

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2024-09-11 13:51 UTC, alexandruradovici requested changes

2024-09-11 13:51 UTC, alexandruradovici commented on capsules/extra/src/servo.rs
> +        }
Not sure we need to do this.

2024-09-11 13:51 UTC, alexandruradovici commented on capsules/extra/src/servo.rs
> +        data2: usize,
`data1` should be the servo, `data2` the angle.

2024-09-11 13:51 UTC, alexandruradovici commented on capsules/extra/src/servo.rs
> +            2 => match self.servo[data2].get_angle() {
This might panic, you can use `.get` instead pf `[]`.

2024-09-11 13:53 UTC, inesmaria08 commented on capsules/extra/src/servo.rs
> +        }
It gives a warning otherwise

2024-09-11 14:09 UTC, inesmaria08 commented on capsules/extra/src/servo.rs
> +            2 => match self.servo[data2].get_angle() {
> This might panic, you can use `.get` instead pf `[]`.

If I write `self.servo.get(servo_index).get_angle()` I get 
```rust 
2 => match self.servo.get(servo_index).get_angle() 
                                       ^^^^^^^^^ method not found in `Option<&&dyn Servo<'a>>`

2024-09-13 11:30 UTC, alexandruradovici requested changes

2024-09-13 11:30 UTC, alexandruradovici commented on capsules/extra/src/servo.rs
> +                if servo_index - 1 >= NUM_SERVO {
The first servo is 0.

2024-09-13 11:30 UTC, alexandruradovici commented on doc/syscalls/90009_servo.md
> +  * ### Command number: `1`
Please update the documentation.

2024-10-15 09:42 UTC, closed without merging